site_name: Datos Económicos UCR
nav:
  - Introducción: index.md
  - Laboratorios:
      - "Semana 4": labs/semana_4.md
      - "Semana 6": labs/semana_6.md
      - "Semana 7": labs/semana_7.md
      - "Semana 8": labs/semana_8.md
      - "Semana 10": labs/semana_10.md
      - "Semana 13": labs/semana_13.md
  - Practicas:
      - "Quiz Stata 1": practicas/stata1.md
  - Videos:
      - "Videos": videos.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - content.code.copy
plugins:
  - search
  - macros
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true

extra_css:
  - stylesheets/add_stylesheet.css
